name: Expression example
on: push
jobs:
  check-expressions:
    runs-on: ubuntu-latest
    steps:
      - name: Check contains
        if: contains('Hello world','Hell')
        run: echo "String contains Hello"
      - name: Check starts with
        if: startswith('Hello world','Hell')
        run: echo "String starts with Hell"
      - name: Check ends with
        if: endswith('Hello world','orld')
        run: echo "String ends with orld"
      - name: Format
        run: echo "${{ format('Hello {0} {1}','Karthik', 'Krithika') }}"
      - name: Convert job context to json
        run : "echo \"Job context to json ${{ toJSON(github.job) }}\""
      - name: Parsed json
        run: "echo \"Parsed JSON ${{ fromJSON('{\"hello\":\"World\"}').hello}}\""
      - name: Success
        if: ${{success()}}
        run: echo "Job ran success"
      - name: Success
        if: ${{failure()}}
        run: echo "Job ran success"
      
