name: Contexts

on:
  push:
    branhces:
      - main

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: My step 1
        run: |
          echo "value of action = $MY_ACTION"
          echo "Value of actor = $MY_ACTOR"
        env:
          MY_ACTION : ${{github.action}}
          MY_ACTOR  : ${{github.actor}}