name: matrix

on:
  workflow_dispatch:

jobs:
  matrix-jobs:
    strategy:
      matrix:
        nodeversions: [10, 12]
    uses: ./printjob.yml@HEAD
    with:
      node: ${{matrix.nodeversions}}