name: matrix

on:
  workflow_dispatch:

jobs:
  matrix-jobs:
    strategy:
      matrix:
        nodeversions: [10, 12]
        subversion  : [1,2,3]
    uses: ./.github/workflows/printjob.yml
    with:
      node: ${{matrix.nodeversions}}
      sub:  ${{matrix.subversion}}