name: Multiple event trigger
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -name: "Multi trigger info"
       run: |
        echo "REF : $GITHUB_REF"
        echo "Job id : $GITHUB_JOB"
        echo "Action : $GITHUB_ACTION"
        echo "Actor : $GITHUB_ACTOR"