# This is a basic workflow to help you get started with Actions
name: Scheduled Event

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/59 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scheduled-jobs-example:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Time tick
        run: echo "Running every 5 minutes"
