name: Actions
#description: 'Checks the custom JS action'

on:
  workflow_dispatch:
    inputs:
      greet-name:
        description: Enter the name
        required: true
        default: ABC

jobs:
  greeting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout job
        uses: actions/checkout@v2
      - name: Trigger action
        id: hello
        uses: ./.github/greet_action
        with:
          greet-name: ${{inputs.greet-name}}
      - name: test-echo
        run: |
          echo "Name given as input is ${{inputs.greet-name}}"
          echo "Name with greet is ${{steps.hello.outputs.greeting}}"


