name: Actions
description: Checks the custom JS action 
on: workflow_dispatch

inputs:
  name:
    description: Enter the name
    required: true
    default: ABC

jobs:
  greeting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout job
        uses: actions/checkout@V3
      - name: test-echo
        run: echo "Name given as input is ${{inputs.name}}"


